// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgyfhtduiamgigpndlgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpneWZodGR1aWFtZ2lncG5kbGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzI0NzUsImV4cCI6MjA2NDI0ODQ3NX0.E3jZ7hqnxB_xXn4FzR57D6YNr1lb1f63eUoGjX7O1d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);